<%@ Page Language="C#" MasterPageFile="~/MP1.Master" AutoEventWireup="true" CodeBehind="CustomerManage.aspx.cs" Inherits="VsProjectSky.CustomerManage" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <form id="form1" runat="server">
        <div style="margin-top:100px;">
            <div>
                <h2 class="text-center title mb-2">Manage Customer</h2>
            </div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Uid" Height="187px" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" BorderStyle="Groove" CellPadding="10" GridLines="None" HorizontalAlign="Center" BorderColor="#3167EB">
                <AlternatingRowStyle ForeColor="Black" />
                <Columns>
                    <asp:BoundField DataField="Uid" HeaderText="User ID" />
                    <asp:BoundField DataField="Username" HeaderText="User Name" />
                    <asp:BoundField DataField="UserFname" HeaderText="First Name" />
                    <asp:BoundField DataField="UserLname" HeaderText="Last Name" />
                    <asp:BoundField DataField="UserPass" HeaderText="User Password" />
                    <asp:BoundField DataField="Addrs" HeaderText="Address" />
                    <asp:BoundField DataField="Sex" HeaderText="Sex" />
                    <asp:BoundField DataField="EmailID" HeaderText="Email ID" />
                </Columns>
                <HeaderStyle BackColor="#3167EB" ForeColor="White" />
                <RowStyle ForeColor="Black" />
                <SelectedRowStyle BorderStyle="None" />
            </asp:GridView>
        </div>
    </form>
</asp:Content>
