<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CustomerManage.aspx.cs" Inherits="VsProjectSky.CustomerManage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Uid" Height="187px" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" Width="978px">
                <Columns>
                    <asp:BoundField DataField="Uid" HeaderText="User ID" />
                    <asp:BoundField DataField="Username" HeaderText="User Name" />
                    <asp:BoundField DataField="UserFname" HeaderText="First Name" />
                    <asp:BoundField DataField="UserLname" HeaderText="Last Name" />
                    <asp:BoundField DataField="UserPass" HeaderText="User Password" />
                    <asp:BoundField DataField="Addrs" HeaderText="Address" />
                    <asp:BoundField DataField="Sex" HeaderText="Sex" />
                    <asp:BoundField DataField="EmailID" HeaderText="Email ID" />
                </Columns>
            </asp:GridView>
        </div>
    </form>
</body>
</html>
