<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="OrderManage.aspx.cs" Inherits="VsProjectSky.OrderManage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>Sky Shop</title>

<!-- jQuery -->
<script src="js/jquery-2.0.0.min.js" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="js/bootstrap.bundle.min.js" type="text/javascript"></script>
<link href="css/bootstrap.css" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">


<!-- custom javascript -->
<script src="js/script.js" type="text/javascript"></script>



    
</head>
<body>
    <form id="form1" runat="server">  
        
        <div>

            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowEditing="GridView1_RowEditing" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting"  OnRowUpdating="GridView1_RowUpdating" CellSpacing="5" DataKeyNames="orderNo" BackColor="White" BorderStyle="Solid" CaptionAlign="Top" CellPadding="3" GridLines="None" >
                <AlternatingRowStyle BackColor="#3399FF" BorderStyle="None" />
                <Columns>
                    <asp:BoundField DataField="orderNo" HeaderText="Order Number" ReadOnly="True" />
                    <asp:BoundField DataField="custid" HeaderText="Customer Id" />
                    <asp:BoundField DataField="amount" HeaderText="Amount" />
                    <asp:BoundField DataField="orderDate" HeaderText="Order Date" />
                    <asp:BoundField DataField="PId" HeaderText="Product Id" />
                    <asp:BoundField DataField="qty" HeaderText="Qty" />
                    <asp:BoundField DataField="prodName" HeaderText="Product Name" />
                    <asp:BoundField DataField="price" HeaderText="Price" />
                    <asp:BoundField DataField="status" HeaderText="Satus" />
                </Columns>
                <HeaderStyle BackColor="#3167EB" BorderStyle="None" ForeColor="White" />
            </asp:GridView>

        </div>
       
    </form>  
</body>
</html>
