<%@ Page Language="C#" MasterPageFile="~/MP1.Master" AutoEventWireup="true" CodeBehind="OrderManage.aspx.cs" Inherits="VsProjectSky.OrderManage" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
   <form id="form1" runat="server">  
        
        <div>

            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowEditing="GridView1_RowEditing" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting"  OnRowUpdating="GridView1_RowUpdating" CellSpacing="5" DataKeyNames="orderNo" BackColor="White" BorderStyle="Solid" CaptionAlign="Top" CellPadding="3" GridLines="None" >
                <AlternatingRowStyle BackColor="#3399FF" BorderStyle="None" />
                <Columns>
                    <asp:BoundField DataField="orderNo" HeaderText="Order Number" ReadOnly="True" />
                    <asp:BoundField DataField="custid" HeaderText="Customer Id" />
                    <asp:BoundField DataField="amount" HeaderText="Amount" />
                    <asp:BoundField DataField="orderDate" HeaderText="Order Date" />
                    <asp:BoundField DataField="PId" HeaderText="Product Id" />
                    <asp:BoundField DataField="qty" HeaderText="Qty" />
                    <asp:BoundField DataField="prodName" HeaderText="Product Name" />
                    <asp:BoundField DataField="price" HeaderText="Price" />
                    <asp:BoundField DataField="status" HeaderText="Satus" />
                </Columns>
                <HeaderStyle BackColor="#3167EB" BorderStyle="None" ForeColor="White" />
            </asp:GridView>

        </div>
       
    </form>
</asp:Content>
