<%@ Page Language="C#" MasterPageFile="~/MP1.Master" AutoEventWireup="true" CodeBehind="PaymentManage.aspx.cs" Inherits="VsProjectSky.PaymentManage" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <form id="form1" runat="server">
        <div class="mx-auto" style="margin-top: 100px; margin-bottom:100px">
                <h2 class="text-center title mb-2">Payment Manage</h2>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" BorderStyle="Groove" CellPadding="10" GridLines="None" HorizontalAlign="Center">
                <AlternatingRowStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="ID" />
                    <asp:BoundField DataField="Cardno" HeaderText="Card Number" />
                    <asp:BoundField DataField="Cardtype" HeaderText="Card Type" />
                    <asp:BoundField DataField="Cardname" HeaderText="Card Name" />
                    <asp:BoundField DataField="Amount" HeaderText="Amount" />
                    <asp:BoundField DataField="Date" HeaderText="Date" />
                    <asp:BoundField DataField="UserName" HeaderText="User Name" />
                    <asp:BoundField DataField="Orderno" HeaderText="Order Number" />
                </Columns>
                <HeaderStyle BackColor="#3167EB" ForeColor="White" />
                <RowStyle BackColor="White" ForeColor="Black" HorizontalAlign="Center" />
            </asp:GridView>
        </div>
    </form>
</asp:Content>
