<%@ Page Language="C#" MasterPageFile="~/MP1.Master" AutoEventWireup="true" CodeBehind="PaymentManage.aspx.cs" Inherits="VsProjectSky.PaymentManage" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
   <form id="form1" runat="server">
        <div class=" m-5 p-5">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Cardno" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" BorderStyle="Solid" CellPadding="3" GridLines="None" HorizontalAlign="Center">
                <AlternatingRowStyle BackColor="#3399FF" ForeColor="White" HorizontalAlign="Center" />
                <Columns>
                    <asp:BoundField DataField="Cardno" HeaderText="Card Number" />
                    <asp:BoundField DataField="Cardtype" HeaderText="Card Type" />
                    <asp:BoundField DataField="validupto" HeaderText="Valid Date" />
                    <asp:BoundField DataField="CVV" HeaderText="CVV" />
                    <asp:BoundField DataField="Cardholder" HeaderText="Card Holder Name" />
                    <asp:BoundField DataField="cardlimit" HeaderText="Card Limit" />
                </Columns>
                <HeaderStyle BackColor="#3167EB" ForeColor="White" />
                <RowStyle BackColor="White" ForeColor="Black" HorizontalAlign="Center" />
            </asp:GridView>
        </div>
    </form>
</asp:Content>
