<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ProductManage.aspx.cs" Inherits="VsProjectSky.ProductManage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" DataKeyNames="PId" OnRowUpdating="GridView1_RowUpdating" BackColor="White" BorderStyle="Solid" BorderWidth="5px" CellPadding="10" GridLines="None" HorizontalAlign="Justify" >
                <AlternatingRowStyle BackColor="#3399FF" ForeColor="White" />
                <Columns>
                    <asp:BoundField DataField="PId" HeaderText="Product ID" />
                    <asp:BoundField DataField="PName" HeaderText="Product Name" />
                    <asp:BoundField DataField="PPrice" HeaderText="Price" />
                    <asp:BoundField DataField="PSelPrice" HeaderText="Selling Price" />
                    <asp:BoundField DataField="PBrandID" HeaderText="Brand ID" />
                    <asp:BoundField DataField="PCategoryID" HeaderText="Category ID" />
                    <asp:BoundField DataField="PDescription" HeaderText="Description" />
                    <asp:BoundField DataField="PImageName" HeaderText="Product Image" />
                </Columns>
                <HeaderStyle BackColor="#3167EB" ForeColor="White" />
                <RowStyle BackColor="White" ForeColor="Black" Wrap="True" />
            </asp:GridView>
        </div>
    </form>
</body>
</html>
