<%@ Page Language="C#" MasterPageFile="~/MP1.Master" AutoEventWireup="true" CodeBehind="ViewCart.aspx.cs" Inherits="VsProjectSky.ViewCart" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            width: 883px;
            height: 53px;
        }
        .auto-style2 {
            height: 196px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
   <form id="form1" runat="server">
       <div class="h-100">
           <div class="auto-style1 h-100 mt-5 ml-5">
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <br />
               &nbsp;&nbsp; Your Cart Products :-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Total Bill Amount :-<asp:Label ID="Label2" runat="server" Text="Label"></asp:Label>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
               <asp:Button ID="Button1" runat="server" Text="Make Payment Now" Width="159px" OnClick="Button1_Click" BackColor="#3167EB" BorderColor="#3399FF" BorderStyle="None" ForeColor="White" Height="32px" />
               <br />
               <br />

           </div>
           <div class="auto-style2 h-100 mb-5 pb-5 ml-5">
               <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting" Height="190px" Width="886px" AutoGenerateColumns="False" CellSpacing="1">
                   <Columns>
                       <asp:BoundField DataField="ProdId" HeaderText="ProductID" />
                       <asp:BoundField DataField="ProName" HeaderText="Product Name" />
                       <asp:BoundField DataField="Price" HeaderText="Price" />
                       <asp:BoundField DataField="Quty" HeaderText="Qty" />
                       <asp:BoundField DataField="PurDate" HeaderText="Purchase Date" />
                   </Columns>
               </asp:GridView>
           </div>
           <asp:Label ID="Label1" runat="server" Text="Label" Visible="False"></asp:Label>

       </div>
    </form>
</asp:Content>
